:recycle: (fish) use eza in fish as well , removes lsd
prasanthrangan/hyprdots pull request #1496
Opened 2024-05-13 12:57 UTC by rubiin

# Pull Request

As we are using `eza` for zsh and `lsd` for fish , it would be better to use `eza` for both as it saves us from trouble of maintaining configs for both

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [x] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [x] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ ] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots
Using `eza` on fish shell

![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/2e08e6e7-ff11-4848-9dc8-ab401a45da08)

(if appropriate)

## Additional context

Add any other context about the problem here.

2024-05-13 13:09 UTC, kRHYME7 commented
difference of both? I  didnt care until now Lol.

2024-05-13 13:10 UTC, rubiin commented
> difference of both? I didnt care until now Lol.

They are the same, replacement for ls  . but eza is more feature rich

2024-05-21 14:54 UTC, rubiin commented
any updates

2024-06-14 14:59 UTC, rubiin commented
any updates on this

2024-07-23 05:58 UTC, abenezerw commented
makes sense i guess, he is just saying using eza for both fish and zsh would reduce the need for an additional lsd config since we are using lsd for fish.

2024-07-24 12:36 UTC, abenezerw commented
> makes sense i guess, he is just saying using eza for both fish and zsh would reduce the need for an additional lsd config since we are using lsd for fish.

Was looking at an install of this hyprdots, and it actually mentions this in the install. 
![IMG_1328](https://github.com/user-attachments/assets/537594a4-e7c3-439b-b16e-7424c130dc24)

2024-08-28 15:52 UTC, rubiin commented
@abenezerw thanks for mentioning that. I will push a fix. Seems I forgot to update a file

2024-08-28 23:53 UTC, kRHYME7 commented on Configs/.config/lsd/colors.yaml
Let's keep the lsd configs for now.

2024-08-29 00:02 UTC, kRHYME7 requested changes
Please bring back the lsd configuration.

2024-08-29 00:02 UTC, kRHYME7 commented on Scripts/restore_cfg.lst
Let's keep the config for now. It might be useful for others.

2024-08-29 00:02 UTC, kRHYME7 commented on Configs/.config/fish/config.fish
Didn't test, but can you confirm that the flags works like lsd or ls?

2024-08-29 08:34 UTC, rubiin commented on Configs/.config/fish/config.fish
yeah . They do

2024-08-29 15:35 UTC, merged