FEAT: adding sticky notes as a keybind
prasanthrangan/hyprdots pull request #1636
Opened 2024-06-29 17:08 UTC by DMelisena

# Pull Request

## Description

A simple sticky notes feature. implementation of https://github.com/prasanthrangan/hyprdots/issues/1635 feature request. this will :

1. install https://github.com/vixalien/sticky from aur as a custom install and keybind it to Super+grave
2. keybind it as a script that check using pgrep, it will spawn if its not opened and close if its already opened
3. customize the apps as float on windows rule

ps: forgive me for not using the template on commit guidelines. I tried to comply with the contribution guideline but seems to miss it out.
this use the same key as quickphrase feature, i think from fcitx5 and will replace it. I never use the quickphrase feature myself though. I asked around and it seems that no one use it anyway.

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [ ] I have added necessary comments/documentation to my code.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

![240629_23h50m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/65994685/4fef6df4-66d5-484b-95db-3ab4d90dca9c)

## Additional context

I missed out the commit message guideline, sorry. I also dont know where window rule should be implemented except on opacity. I Will suggest a documentation update if this seems to be applicable. This is my first try on contributing to an opensource so i wish for guidance.

2024-07-21 09:46 UTC, Enigma1309 commented
can we add support for flatpak app too?

2024-07-21 09:51 UTC, kRHYME7 requested changes

2024-07-21 09:51 UTC, kRHYME7 commented on Scripts/custom_hypr.lst
> +aur:sticky-notes                                       # ide text editor
Should be in ` ./custom_apps.lst ` for optional packages

2024-07-23 04:28 UTC, mahaveergurjar commented
Please add this package in `./custom_apps.lst` don't add in `./custom_hypr.lst`

2024-12-12 17:29 UTC, T-Crypt commented
Fix conflicts and add package to custom_apps.lst

2024-12-12 17:29 UTC, closed without merging