Feature : Show 10 notification history in tooltip
prasanthrangan/hyprdots pull request #1715
Opened 2024-07-29 13:39 UTC by mahaveergurjar

# Pull Request

## Description
Show notification  history  uptop 10 notifications

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [x] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots
![240722_19h47m24s_screenshot](https://github.com/user-attachments/assets/dec913dc-a56b-4b71-b710-05dc88ee9578)
![image](https://github.com/user-attachments/assets/b16d794a-8628-4198-aed7-7f451b052eb1)

(if appropriate)

## Additional context

Add any other context about the problem here.

2024-07-29 13:40 UTC, mahaveergurjar commented
@kRHYME7 review please this pr

2024-07-29 13:50 UTC, kRHYME7 commented
Can you try to add maybe bullet? for each notifs

2024-07-29 14:28 UTC, mahaveergurjar commented
ok

2024-07-29 14:34 UTC, mahaveergurjar commented
![image](https://github.com/user-attachments/assets/793aa569-49c2-43bc-9a3b-ceedb3dac604)
![image](https://github.com/user-attachments/assets/8c0072b8-4099-4b9d-91fe-b5ea388d33ef)
![image](https://github.com/user-attachments/assets/3f597647-2cf3-45c5-9df4-f76029357f46)
which on is add ???

2024-07-29 14:41 UTC, kRHYME7 commented
1st I guess. Just make it simple. Tnx

2024-07-29 14:49 UTC, mahaveergurjar commented
ok
I add

2024-07-29 14:55 UTC, mahaveergurjar commented
@kRHYME7 know test added all things

2024-07-31 03:27 UTC, mahaveergurjar commented
@kRHYME7 please review this pr

2024-07-31 04:39 UTC, kRHYME7 requested changes

2024-07-31 04:39 UTC, kRHYME7 commented on Configs/.local/share/bin/notifications.py
> -    tooltip_click.append("󰳽 click-left:  history pop")
Can you also add this line 
    
``` tooltip_click.append("󰳽 scroll-down:  history pop") ```

2024-07-31 04:49 UTC, mahaveergurjar commented
Ok

2024-07-31 08:33 UTC, mahaveergurjar commented
Added

2024-08-04 07:55 UTC, mahaveergurjar commented
@kRHYME7 please review this pr

2024-08-04 10:53 UTC, hdengsan commented
What about using the sway notification center and just theme it. It's already a dependency. It will handle this better than some bash scripts.

2024-08-06 19:05 UTC, Sitolam approved these changes

2024-08-10 08:11 UTC, kRHYME7 approved these changes
Thanks!

2024-08-10 08:11 UTC, merged

2024-08-10 09:05 UTC, mahaveergurjar commented on Configs/.local/share/bin/notifications.py
> +    tooltip_click.append("󰳽 scroll-down:  history pop")
I removed it but I  think it does not remove

2024-08-10 10:16 UTC, kRHYME7 commented on Configs/.local/share/bin/notifications.py
> +    tooltip_click.append("󰳽 scroll-down:  history pop")
I think it's fine now?