cleaner volume script for extensibility and swayosd integration
prasanthrangan/hyprdots pull request #1835
Opened 2024-09-13 05:45 UTC by keth-real

# Pull Request

## Description
A different approach from this https://github.com/prasanthrangan/hyprdots/pull/1818.
This way we can adhere to the original script without breaking legacy functions. 

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [x] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [x] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added a changelog entry.
- [x] I have added necessary comments/documentation to my code.
- [x] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

## Screenshots

(if appropriate)

## Additional context

This PR is not yet complete and will be discussed here https://github.com/prasanthrangan/hyprdots/pull/1818

2024-09-13 05:48 UTC, kRHYME7 commented
damn, another 1. 

@rubinV @TheyCallMeSecond

Can you alsoe please check this one? This one has a good approach though, without changing the keybindings.conf.

2024-09-13 10:01 UTC, kRHYME7 commented
Will draft first. Updraft when ready. Thanks!

2024-09-13 13:22 UTC, kRHYME7 requested changes

2024-09-13 13:22 UTC, kRHYME7 commented on Configs/.local/share/bin/brightnesscontrol.sh
Cool, Please make the script consistent with the volumescript. Thanks!

2024-09-13 16:36 UTC, keth-real commented
Ready for testing @rubiin  @kRHYME7

2024-09-13 16:43 UTC, rubiin commented
When you say extensible is it backward compatible ?

2024-09-13 16:56 UTC, keth-real commented
> When you say extensible is it backward compatible ?

The existing version supports the older script, which can be confusing and makes it difficult for other contributors to understand. Additionally, I have fixed the -p player option and implemented fixes for the toggle mute for -p. The older script relies on the action_function format, where the function is from another variable, leading to unnecessary confusion.

2024-09-13 17:10 UTC, rubiin commented
Cool. Will give it a try tomorrow and get back to you.

2024-09-13 17:55 UTC, kRHYME7 commented
```
# exec-once = pkexec swayosd-libinput-backend | - # swayosd service for keyboard input. Need to add the '| -' for now so the daemon won't exit 
```

Note we can run the daemon on user level but we need to trick this deamon as this is intended to run using systemctl
We  can trick it by piping it somewhere  

we can use | something 
or we can  use && or || or any ways we can execute a subshell while invokinh swayosd-libinput-backend

This way swayosd-libinput stays on the user level.


I'm just amaze with this bug.

2024-09-14 16:59 UTC, kRHYME7 commented
@rubiin  This works on my end. Also, swayosd is snappier than other OSD I tried.

2024-09-14 17:30 UTC, rubiin commented
> @rubiin This works on my end. Also, swayosd is snappier than other OSD I tried.

works on mine too

2024-09-15 03:06 UTC, kRHYME7 commented
This works as intended and shouldn't give problems if users do not have Swayosd.

We can Merge this first then refine the other PR? How about that?

2024-09-15 11:09 UTC, rubiin commented
Lets get this merged

2024-09-15 12:23 UTC, kRHYME7 approved these changes
💗

2024-09-15 12:23 UTC, merged