[theme maintainers] option to strictly implement colors for themes
prasanthrangan/hyprdots pull request #1905
Opened 2024-10-05 08:59 UTC by keth-real

# Pull Request

## Description

Closes https://github.com/prasanthrangan/hyprdots/issues/1904
Prevents [confusion with theme mode and wallbash mode ](https://github.com/prasanthrangan/hyprdots/pull/1889) 

Reason: 
It's the feat req of Khing. 
This way theme maintainers can optionally ship the intended dominant color files.  

TODO: 

* themepatcher.sh should support if file exist
* Hyde theme import should also be updated

2024-10-05 09:01 UTC, kRHYME7 commented
Should adjust the themepatcher script. I'll update the 
Hyde theme import first then you can copy it.

2024-10-05 09:02 UTC, kRHYME7 requested changes

2024-10-05 09:02 UTC, kRHYME7 commented on Configs/.local/share/bin/swwwallbash.sh
> +if [ -f "${hydeThemeDir}/theme.dcol" ]; then
only do this idf enableWallDcol is set for theming.

2024-10-05 09:06 UTC, kRHYME7 commented
@keth-real  https://github.com/HyDE-Project/Hyde-cli/commit/55f51e4e160cdfe248913bf797aee2b7ce139fa7

Please add this to the themepatcher in this repo

2024-10-05 09:49 UTC, kRHYME7 commented
Also for theme maintainers:  
It should work like this. 
Make a ./theme.dcol  with the best colors that reflects your theme. 

https://github.com/HyDE-Project/hyde-gallery/commit/bcda9ae84897501ee458b501296bee26f754910b
![image](https://github.com/user-attachments/assets/44d19670-7e14-45cc-8165-634e67431586)


@rubiin  @abenezerw  @mahaveergurjar  @rishav12s

2024-10-05 09:49 UTC, kRHYME7 approved these changes

2024-10-06 04:18 UTC, kRHYME7 commented
Will drop this here for now

https://gist.github.com/kRHYME7/b41de939393218f1abcb5f826150583e
![Uploading image.png…]()

2024-10-06 04:20 UTC, merged

2024-10-06 04:21 UTC, mahaveergurjar commented
and what about dunst notification theme ??? its only follow walbash theme

2024-10-06 04:39 UTC, kRHYME7 commented
> ? its only follow walbash theme

Anything that follows with the wallpaper colors can be overridden with the ` theme.dcol` file  so for dunst or any other elements as long as the theme.dcol is available they will use it instead of the cached wallpapaper dominant colors (wall.dcol)

2024-10-06 04:40 UTC, mahaveergurjar commented
ok

2024-10-06 04:44 UTC, kRHYME7 commented
I updated the gist. 

![Uploading image.png…]()

In short `theme.dcol` is just `wall.dcol ` that is shipped by the theme.

2024-10-06 04:46 UTC, mahaveergurjar commented
ok

2024-10-06 04:54 UTC, mahaveergurjar commented
![image](https://github.com/user-attachments/assets/723bcbe3-518c-4885-aecf-55de98144945)
 link to which file ?? so these are color are overide @kRHYME7

2024-10-06 05:04 UTC, kRHYME7 commented
no need for the header line as this is sourced like how the script source the current wallpaper dcol.

2024-10-06 05:05 UTC, mahaveergurjar commented
ok

2024-10-06 05:09 UTC, mahaveergurjar commented
so now in theme not need waybar. theme or kitty.theme these theme value are also pick from theme.dcol ?? only need theme only need hypr.theme for change blur or other things right

2024-10-06 05:44 UTC, kRHYME7 commented
@mahaveergurjar  We still love to have them. 

In theme mode  you can tweak the colors for each target files which very flexible.

waybar.theme
rofi.theme
etc.theme

But we cannot modify other templates (outside the theme) right? As they are using wall.dcol, and we cannot modify wall.dcol as this is cache per wallpaper

What we did is adding our own version of the wall.dcol file called "theme.dcol"

Now even if we can't modify other templates (dunst,cava,discord etc outside the scope of the theme), we can still tweak their colors by overriding the sourced colors of wall.dcol by "theme.dcol"  file. Making the theme more consistent...

2024-10-06 06:06 UTC, kRHYME7 commented
# For this example, I am using swaync wallbash template. Note that this template is dynamic so by default it follows the wallpapers even in theme mode 

## With "theme.dcol" file. 
![image](https://github.com/user-attachments/assets/714efbf1-1b24-497b-bbbe-3eebfaf7ae17)

Even if a theme, do not have "swaync.theme". 
We can tweak the colors by using "theme.dcol" 
This will give consistent elements, In this illustration swaync matches with waybar. 


## Without theme.dcol 
![image](https://github.com/user-attachments/assets/6ffb45bb-d8c4-49b4-ac5d-44cbfb5f9538)

This is the default scenario where there is no "theme.dcol"
All templates that are not declared by *.theme will follow the wallpaper. 
For example, swaync looks different with waybar and the kitty terminal. 







Either way both aims to have an aesthetic impact, so theme maintainers should use this wisely.

2024-10-06 06:29 UTC, mahaveergurjar commented
I mean add these in theme.dcol so define the kitty, waybar color in theme.dcol.so.its easy to use only one file for all  if wallbash off thene theme.dcol color follow of wallbash on then wallbash colour follow

2024-10-06 07:12 UTC, kRHYME7 commented
> I mean add these in theme.dcol so define the kitty, waybar color in theme.dcol so its easy to use only one file for all if wallbash off then theme.dcol color follow if wallbash on then wall.dcol colour follow

We can't, theme.dcol are just variables in bash and this is being sourced. The same as the wall.dcol. We can't extend its functionality that much. 

But in your kitty.theme, waybar.theme and other *.theme you can put  <wallbash_*> placeholder in it instead of hardcoded colors.  (works the same as wallbash mode) but is controlled by the theme. 

So for the "*.theme" templates you can have a mixed of <wallbash_*> placeholder  plus some hardcoded once. 
Then if you tweak it you can just do it in theme.dcol by playing around with the  `dcol_= values`

2024-10-06 08:38 UTC, mahaveergurjar commented
Ok

2024-10-06 08:54 UTC, mahaveergurjar commented
Its good all are follow color strictly
![image](https://github.com/user-attachments/assets/8298425c-212b-4518-bfac-a46a354a4314)
![image](https://github.com/user-attachments/assets/d13ffc00-5e2d-429d-99f9-be40070e6378)
![image](https://github.com/user-attachments/assets/24a27981-b3e4-4bec-8180-263cb6af0e3d)

2024-10-06 10:38 UTC, kRHYME7 commented
@mahaveergurjar  Lovely! Will you update it in the theme repo?

2024-10-06 10:45 UTC, mahaveergurjar commented
Ok but i don't completely port all color in theme.dcol

2024-10-06 10:55 UTC, mahaveergurjar commented
@kRHYME7 I am updated the repo you can fetch the theme

2024-10-06 11:06 UTC, kRHYME7 commented
> Ok but i don't completely port all color in theme.dcol


Should still be fine theme.dcol will just override any duplicates. 


BTW please comment out some excess lines, it is the same with bash.  so use # as comments
![image](https://github.com/user-attachments/assets/d18139f4-1a5d-4bf6-a3c4-cbca1692a29d)

2024-10-06 11:11 UTC, mahaveergurjar commented
ok

2024-10-06 11:26 UTC, mahaveergurjar commented
Fixed @kRHYME7 please test it work or not properly