print focused monitor or window
prasanthrangan/hyprdots pull request #301
Opened 2023-10-06 23:29 UTC by stove-jeebs

1. I haven't modified or added any screenshot keybindings, as I prefer to use my own custom settings. I believe the choice of keybindings is best left to the individual 
2. I frequently upload my screenshots to Discord. Having to manually delete them each time can be cumbersome. Therefore, instead of storing screenshots in $save_dir, I've chosen to use Swappy, which gives users the option to save or simply copy the screenshot.
3. I've updated the default save directory (`$save_dir`) to ~/Pictures/screenshots to account for the likelihood of users storing varied image types in ~/Pictures, beyond just screenshots.

2023-10-07 00:43 UTC, stove-jeebs commented
I've made changes to the script in an attempt to resolve issue #214, specifically problem 3:

> something I personally find really frustrating about screenshot snip is that it currently doesn't "snapshot"/freeze the screen in place. For example, I wouldn't be able to snip a tooltip because the moment I press the screenshot key bind it unhovers the tooltip

However, I'm not entirely satisfied with the outcome and am unsure about committing these changes. Do you have any recommendations?

`~/.config/hypr/scripts/screenshot.sh`:
```bash
# screenshot snip
s)  mkdir -p $swpy_dir
    echo -e "[Default]\nsave_dir=$save_dir\nsave_filename_format=$save_file" > $swpy_dir/config
    temp_screenshot="/tmp/fullscreen_screenshot.png"
    hyprctl keyword animations:enabled 0
    # Capture the full screen of the active monitor
    grim -o "$(hyprctl -j activeworkspace | jq -r '.monitor')" "$temp_screenshot"
    # Open the screenshot in imv (in the background)
    imv -f "$temp_screenshot" &
    IMV_PID=$!
    # Capture the desired region
    screenshot_region=$(slurp)
    kill $IMV_PID
    sleep 0.2
    grim -g "$screenshot_region" - | swappy -f -
    hyprctl keyword animations:enabled 1
    rm "$temp_screenshot" ;;
```

2023-10-07 02:53 UTC, stove-jeebs commented
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/8e440a9f-d0df-4837-b864-a4f0bf6a2f33)
sometimes I get this from running the code above

2023-10-07 15:27 UTC, prasanthrangan commented
> sometimes I get this from screenshots using the script above

i think its cropping the selected area from both monitor??
Let me try this out...

2023-10-09 14:47 UTC, kRHYME7 commented
> I've made changes to the script in an attempt to resolve issue #214, specifically problem 3:
> 
> > something I personally find really frustrating about screenshot snip is that it currently doesn't "snapshot"/freeze the screen in place. For example, I wouldn't be able to snip a tooltip because the moment I press the screenshot key bind it unhovers the tooltip
> 
> However, I'm not entirely satisfied with the outcome and am unsure about committing these changes. Do you have any recommendations?



HELLO! Found something useful 

[grimblast](https://github.com/hyprwm/contrib
)


did not tinker around it but got excited to share here.

2023-10-09 23:57 UTC, stove-jeebs commented
@kRHYME7 Thank you! This is just what I need

2023-10-11 03:47 UTC, kRHYME7 reviewed
Can We use 
 ```savecopy``` on grimblast?

2023-10-11 15:57 UTC, prasanthrangan commented
Hi @stove-jeebs and @kRHYME7 , are you guys still working on this? or is it ready to merge??
Sorry, I didn't get a chance to test this out yet...

2023-10-11 16:00 UTC, prasanthrangan commented on Configs/.config/waybar/modules/idle_inhibitor.jsonc
>          }
wont this increase the space between the icon and the clock? each module is padded already.

2023-10-11 17:12 UTC, kRHYME7 commented on Configs/.config/hypr/scripts/screenshot.sh
> +    XDG_PICTURES_DIR="$HOME/Pictures/screenshots/"
I think we should use    ```  XDG_PICTURES_DIR="$HOME/Pictures" ``` here

2023-10-11 17:31 UTC, kRHYME7 requested changes
@stove-jeebs  Thanks! I put some comments on some lines

Is it possible to organize our PR on a separate branch/project and be specific on a certain task? 

Thanks for the hard work!

2023-10-11 17:31 UTC, kRHYME7 commented on Scripts/custom_hypr.lst
> +imv
IMO, image viewer is by the $USER preference @stove-jeebs

2023-10-11 17:31 UTC, kRHYME7 commented on Configs/.config/hypr/scripts/screenshot.sh
> +    XDG_PICTURES_DIR="$HOME/Pictures/screenshots/"
I think we should use    ```  XDG_PICTURES_DIR="$HOME/Pictures" ``` here

And 

put the folder  in ``` save_dir="${2:-$XDG_PICTURES_DIR/Screenshots}```
And use sentence case for the directory.

2023-10-11 17:54 UTC, T-Crypt commented on Configs/.config/waybar/modules/updates.jsonc
> +        "interval": 3600, // once every hour
This is probably his user preference here -- 1 hour is a bit too much. 

Also, should be separate pull request as this is for Snip tool and not the updates module -- should be moved to separate branch for this.

We should leave this interval at 86400 -- Once Per Day

2023-10-11 17:56 UTC, T-Crypt requested changes
Fix  `updates.jsonc` to 86400 // once every day

2023-10-11 20:35 UTC, stove-jeebs commented
> Note: I haven't modified or added any screenshot keybindings, as I prefer to use my own custom settings. I believe the choice of default keybindings is best left to the creator

Initially, I didn't want to add my bindings since it might convolute the default bindings, but there is a duplicated binding... If it doesn't serve any purpose I'll change `screenshot.sh p` to `screenshot.sh m`

![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/410c538e-8621-477a-ab94-bd567bff94f0)

2023-10-11 20:45 UTC, stove-jeebs commented
> @stove-jeebs Thanks! I put some comments on some lines
> 
> Is it possible to organize our PR on a separate branch/project and be specific on a certain task?
> 
> Thanks for the hard work!

I'm still new to collaborating on GitHub so I'm not exactly familiar with how this is done

2023-10-12 14:01 UTC, prasanthrangan commented on Configs/.config/hypr/scripts/screenshot.sh
>      echo -e "[Default]\nsave_dir=$save_dir\nsave_filename_format=$save_file" > $swpy_dir/config
this line should be before the case statement for swappy to work, else it will overwrite previous file.

2023-10-14 19:40 UTC, prasanthrangan commented
oh no conflicts, due to my latest commit.

2023-10-15 05:29 UTC, prasanthrangan commented
Hi, I've resolved the conflict manually in 0a7b0c3.

2023-10-15 05:29 UTC, closed without merging